### PR TITLE
Add logo files

### PR DESCRIPTION
**Pull request by illusional**
Hello WDL community and also specifically @patmagee @geoffjentry and @davycats,

This PR follows the conversation from https://github.com/openwdl/wdl/issues/341.

I'd like to contribute a few vector logo files for OpenWDL. I've tried to replicate the existing logo, but attempted to tighten the connections for symmetry. I've also created a dark / invert copy, though I'm open to critique on that.

### Original
65FFA9C0C26FAD90

I added a super short README within the logo folder with some information:

**Font**: Courier (including the brackets)
**Primary color**: `#009abf` (the website uses `#3097ba`)

Recommended invert background: `#262626`

Each folder contains:

- `.ai`: Adobe Illustrator file
- `.svg`: Scalable Vector Graphic
- `.png`: Full scale export with alpha
- primary / invert: `-preview.png`: PNG export with background

#### Logo
wdl-logo-preview

#### Invert

wdl-logo-invert-preview

## Major modification

In addition, I was playing around and found a cool-looking modification with the padding. I this changes gives the logo a cool geometric feel, I've included it here per the discussion on https://github.com/openwdl/wdl/issues/341.

#### Logo

wdl2-preview

#### Invert

wdl2-invert-preview

### CODE REVIEW

**Comment by patmagee** [comment]
This is great! Thanks for putting this togetehr @illusional. My personal preference is for the Modified versions of the logos, but lest see what others things

**Comment by patmagee** [comment]
@illusional it looks like the actual inverted images in the repo do not have an inverted background but a transparent one

**Comment by illusional** [comment]
Thanks @patmagee! I've hidden the background (and allowed transparency) for the invert export  so it can be used on darker slides that aren't the exact color, but I've put a `-preview.png` in there to show how it might look. Depends on the community, but it might be worth writing a branding guide, then I'd say it'd be good to generate the logo with the proper background.

**Comment by orodeh** [comment]
Thanks! looks good to me 👍

**Comment by geetduggal** [comment]
Love the major mod one!

**Comment by pshapiro4broad** [comment]
It looks to me like the redesign loses an important part of the original. In the original logo, the paths connecting the hexagons can be seen as directional, due to the way that the connecting lines are attached on one end and not on the other. This directionality was lost in the first recreated icon -- the top and bottom nodes both point at the middle node -- and never added back.

Was this change intentional? To me, this change loses a depiction of WDL's node dependency graph.

**Comment by illusional** [comment]
Hey @pshapiro4broad, you're very right and I hadn't noticed (I think I had sort of assumed left-to-right workflows), so I've pushed new files to better replicate the original logo, here they are below. 

**Icon**



**Logo**


**Inverse logo**


I think it's certainly worth highlighting the roots of the original, and that would be lost if switched to the redesigned one.

**Comment by pshapiro4broad** [comment]
Thanks, this looks much better to me.

**Comment by patmagee** [comment]
This does look great, and @pshapiro4broad I never though about the directed nature of the logo but it makes total sense.

@illusional I'm just noticing now, but it looks like there is a veeeeeeerrryy tiny line, between the first hexagon and its edge.

**Comment by illusional** [comment]
@patmagee this was strange, because the shapes definitely connected in illustrator but outside the gap appeared. I've made a compound shape to resolve this, though ideally I probably should've just handwrote the SVG like in https://github.com/openwdl/wdl/issues/341#issuecomment-555470166.

I've updated the repo, and here are the newer images:

**Icon**



**Logo**



**Inverse logo**

**Comment by patmagee** [comment]
@illusional these look bette! no extra line at all!

**Comment by DavyCats** [comment]
This is looking great! :+1:

**Comment by illusional** [comment]
Hey @patmagee, just wondering where this PR should go? If there's support, I think it would be good to produce a branding guideline about colors, fonts and icon usage.

**Comment by patmagee** [comment]
@illusional This PR has gotten very little attention, but it seems we have support for the updated images you recently posted to proceed as the official images of WDL. Lets open this up for voting unless there are any additional changes you would like to make?

Merging this would also coincide with updating the website, which I have moved to git pages (not sure if @vdauwera has updated the DNS record):  https://stackoverflow.blog/2010/10/21/when-will-my-site-graduate/

**Comment by cjllanwarne** [comment]
👍 and thank you!

**Comment by patmagee** [comment]
:+1:

**Comment by vdauwera** [comment]
:+1: from me, nice to see the logo evolve to suit the community :)

Just updated the DNS records so openwdl.org points to the new site, so great timing indeed.

**Comment by pshapiro4broad** [comment]
👍

**Comment by orodeh** [comment]
👍

**Comment by DavyCats** [comment]
:+1:

**Comment by aednichols** [comment]
👍

**Pull request merged**
